[context.production]
  command = "yarn build && cp .netlify/_headers public/_headers && cp .netlify/_redirects public/_redirects"
  publish = "public/"

[context.deploy-preview]
  command = "yarn build && cp .netlify/_headers public/_headers && cp .netlify/_redirects public/_redirects"
  publish = "public/"

[context.develop]
  command = "yarn build && cp .netlify/_headers public/_headers && cp .netlify/_redirects public/_redirects"
  publish = "public/"

[[redirects]]
  from = "/technologies/signer"
  to = "https://signer.parity.io"
  status = 301
  force = true

[[redirects]]
  from = "/technologies/signer/"
  to = "https://signer.parity.io"
  status = 301
  force = true

[[redirects]]
  from = "/signer"
  to = "https://signer.parity.io"
  status = 301
  force = true

[[redirects]]
  from = "/signer/"
  to = "https://signer.parity.io"
  status = 301
  force = true
