name: Call reusable workflow to add PRs to Web project board 

on:
  pull_request:
    types:
      - opened

jobs:
  call-add-prs-to-project:
    uses: w3f-webops/infrastructure/.github/workflows/add-prs-to-project.yml@main
    secrets:
      app_id: ${{ secrets.APP_ID }}
      private_key: ${{ secrets.PRIVATE_KEY }}
    with:
      project-url: https://github.com/orgs/paritytech/projects/44
